color0 #371b2a
color1 #fd4663
color2 #efa2ca
color3 #e9a8aa
color4 #e7c7aa
color5 #ec92c1
color6 #e99698
color7 #f3f2f2
color8 #71626a
color9 #fd4663
color10 #efa2ca
color11 #e9a8aa
color12 #e7c7aa
color13 #ec92c1
color14 #e99698
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #29141f
background            #29141f
foreground            #f3f2f2
selection_foreground  #b6afb3
selection_background  #371b2a
active_border_color   #efa2ca
inactive_border_color #452134
url_color             #efa2ca

active_tab_foreground   #25181f
active_tab_background   #efa2ca
inactive_tab_foreground #b6afb3
inactive_tab_background #452134
cursor_trail_color      #b6afb3
