-- neovim.lua — auto-generated by iNiR. Use 99-inir-user.lua for overrides.
return {
  {
    "yukazakiri/inir.nvim",
    priority = 1000,
    opts = {},
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "inir",
    },
  },
}
